version: "3.8"

services:
  psql-db:
    image: postgres
    container_name: psql-db
    restart: always
    environment:
      POSTGRES_USER=postgres
      POSTGRES_PASSWORD=postgres
      POSTGRES_DB=spring-docker
    ports:
      "5432:5432"
    volumes: 
      - ./data:/var/lib/postgresql/data
  backend:
    container_name: backend
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL=jdbc:postgresql://psql-db:5432/spring-docker
      SPRING_DATASOURCE_USERNAME=postgres
      SPRING_DATASOURCE_PASSWORD=postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - psql-db
